import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar } from "lucide-react";
import { format } from "date-fns";

export default function GeneratedReports({ reports, user }) {
  const downloadReport = (report) => {
    const reportText = `
INTELLIGENCE REPORT
${report.report_title}
Generated: ${format(new Date(report.report_date), "PPP")}
Classification: ${report.classification.toUpperCase()}

EXECUTIVE SUMMARY
${report.executive_summary || "N/A"}

KEY FINDINGS
${(report.key_findings || []).map((f, i) => `${i + 1}. ${f}`).join("\n")}

THREAT LANDSCAPE
Overall Threat Level: ${report.threat_landscape?.overall_threat_level || "N/A"}
Active Threats: ${report.threat_landscape?.active_threats || 0}
High Priority Threats: ${report.threat_landscape?.high_priority_threats || 0}

RECOMMENDATIONS
${(report.recommendations || []).map((r, i) => `${i + 1}. [${r.priority}] ${r.recommendation}\n   Rationale: ${r.rationale}`).join("\n\n")}

AI INSIGHTS
${report.ai_insights?.pattern_analysis || "N/A"}

Generated by: ${report.generated_by || "System"}
    `.trim();

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `intelligence-report-${format(new Date(report.report_date), "yyyy-MM-dd")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getClassificationColor = (classification) => {
    switch (classification) {
      case "restricted": return "bg-red-500/20 text-red-400";
      case "confidential": return "bg-amber-500/20 text-amber-400";
      case "internal": return "bg-cyan-500/20 text-cyan-400";
      default: return "bg-gray-500/20 text-gray-400";
    }
  };

  return (
    <Card className="border-[#1a1a1a] bg-[#0f0f0f]">
      <CardHeader>
        <CardTitle className="text-white flex items-center gap-2">
          <FileText className="w-5 h-5" />
          Generated Reports
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          {reports.map((report) => (
            <Card key={report.id} className="border-[#1a1a1a] bg-[#0a0a0a]">
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <h3 className="font-bold text-white">{report.report_title}</h3>
                      <Badge className={getClassificationColor(report.classification)}>
                        {report.classification}
                      </Badge>
                      <Badge variant="outline">{report.report_type.replace(/_/g, " ")}</Badge>
                    </div>

                    <div className="grid md:grid-cols-3 gap-3 text-sm mb-3">
                      <div>
                        <p className="text-gray-400">Generated</p>
                        <div className="flex items-center gap-1">
                          <Calendar className="w-3 h-3 text-cyan-400" />
                          <p className="text-white font-semibold">
                            {format(new Date(report.report_date), "MMM d, yyyy")}
                          </p>
                        </div>
                      </div>
                      <div>
                        <p className="text-gray-400">Period</p>
                        <p className="text-white font-semibold">
                          {report.time_period?.start_date 
                            ? format(new Date(report.time_period.start_date), "MMM d") + " - " + 
                              format(new Date(report.time_period.end_date), "MMM d")
                            : "N/A"}
                        </p>
                      </div>
                      <div>
                        <p className="text-gray-400">Key Findings</p>
                        <p className="text-white font-semibold">{report.key_findings?.length || 0}</p>
                      </div>
                    </div>

                    {report.executive_summary && (
                      <p className="text-sm text-gray-400 mb-2 line-clamp-2">
                        {report.executive_summary}
                      </p>
                    )}

                    {report.threat_landscape && (
                      <div className="flex gap-2">
                        <Badge className="bg-red-500/20 text-red-400">
                          Threat Level: {report.threat_landscape.overall_threat_level}
                        </Badge>
                        <Badge className="bg-amber-500/20 text-amber-400">
                          Active: {report.threat_landscape.active_threats}
                        </Badge>
                      </div>
                    )}
                  </div>

                  <Button
                    size="sm"
                    onClick={() => downloadReport(report)}
                    className="bg-cyan-600 hover:bg-cyan-700 ml-4"
                  >
                    <Download className="w-4 h-4 mr-1" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}

          {reports.length === 0 && (
            <div className="text-center py-12">
              <FileText className="w-16 h-16 text-gray-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-white mb-2">No Reports</h3>
              <p className="text-gray-400">Generate your first intelligence report</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}